# Generated by Django 4.2.1 on 2023-06-23 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='servicios_seleccionados',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_carrito',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
