# Generated by Django 4.2.1 on 2023-06-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
    ]
